version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
      nodejs: 12
    commands:
      - yum install -y tar
      - |
        if [ -e /tmp/composer.lock ] ; then
          echo 'exists /tmp/compsoer.lock'
        else
          echo 'not exists /tmp/composer.lock'
        fi
      - |
        if [ -e /tmp/vendor.tar ] ; then
          echo 'exists /tmp/vendor.tar'
        else
          echo 'not exists /tmp/vendor.tar'
        fi
      - |
        if [ -e /tmp/composer.lock ] && [ -e /tmp/vendor.tar ]; then
          diff /tmp/composer.lock ./src/composer.lock
          if [$? -eq 0]; then
            tar xf /tmp/vendor.tar -C ./src
          fi
        fi
      - |
        if [ -e ./src/vendor ]; then
          echo 'exists ./src/vendor'
        else
          echo 'not exists ./src/vendor'
        fi
      - |
        if [ ! -e ./src/vendor ]; then
          yum install -y php-mbstring php-xml php-bcmath
          yum install -y tar
          curl -sS https://getcomposer.org/installer | php
          cp composer.phar /usr/local/bin/composer
          unlink /usr/bin/composer
          ln -s /usr/local/bin/composer /usr/bin/composer
          yum install -y git
          yum install -y zip unzip
        fi
  build:
    commands:
      - cd src/
      - rm -rf .git .gitignore README.md
      - |
        if [ ! -e ./vendor ]; then
          composer install
        fi
      - npm install
      - npm run production
  post_build:
    commands:
      - php artisan cache:clear
      - php artisan config:clear
      - ./vendor/bin/phpunit
      - cp composer.lock /tmp
      - tar cf /tmp/vendor.tar vendor

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - /tmp/composer.lock
    - /tmp/vendor.tar