version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
      nodejs: 14
    commands:
      - |
          yum install -y php-mbstring php-xml php-bcmath

          curl -sS https://getcomposer.org/installer | php
          cp composer.phar /usr/local/bin/composer
          ln -s /usr/local/bin/composer /usr/bin/composer

          yum install -y git
          yum install -y zip unzip
  build:
    commands:
      - cd src/
      - rm -rf .git .gitignore README.md
      - composer install
      - npm install
      - npm run production
  post_build:
    commands:
      - php artisan cache:clear
      - php artisan config:clear
      - ./vendor/bin/phpunit

artifacts:
  files:
    - '**/*'