version: 0.2

phases:
  install:
    commands:
      - |
          amazon-linux-extras install php7.3 -y
          yum install -y php-mbstring php-xml php-bcmath

          curl -sS https://getcomposer.org/installer | php
          cp composer.phar /usr/local/bin/composer
          ln -s /usr/local/bin/composer /usr/bin/composer

          yum install -y git
          yum install -y zip unzip
      - curl -sL https://rpm.nodesource.com/setup_12.x | bash -
      - yum install --enablerepo=nodesource nodejs -y
  build:
    commands:
      - cd src/
      - rm -rf .git .gitignore README.md
      - composer install
      - npm install
      - npm run production

artifacts:
  files:
    - '**/*'