version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
      nodejs: 12
    commands:
      - yum install -y php-mbstring php-xml php-bcmath
      - curl -sS https://getcomposer.org/installer | php
      - cp composer.phar /usr/local/bin/composer
      - unlink /usr/bin/composer
      - ln -s /usr/local/bin/composer /usr/bin/composer
      - yum install -y git
      - yum install -y zip unzip
  pre_build:
    commands:
      - cd src/
      - cp -r /tmp/.composer_cache/ ./.composer
  build:
    commands:
      - rm -rf .git .gitignore README.md
      - composer install
      - npm install
      - npm run production
  post_build:
    commands:
      - php artisan cache:clear
      - php artisan config:clear
      - ./vendor/bin/phpunit
      - cp composer.lock

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - /tmp/.composer/**/*