version: '3'

services:
  php:
    build:
      context: ./docker/apache
    volumes:
      - ./src/:/var/www/html
    ports:
      - 8080:80
    container_name: tw-clone-php

  mysql:
    image: mysql:5.7.16
    volumes:
      - ./docker/mysql/volume:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tw_clone
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    container_name: tw-clone-mysql
